[project]
name = "senior-project-resource-and-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chronos-forecasting>=2.3.2",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "statsmodels>=0.15.0",
    "tensorflow>=2.21.0",
    "torch>=2.14.0",
    "xgboost>=3.4.1",
]
